name: gallery
description: A resource to help developers evaluate and use Flutter.
repository: https://github.com/flutter/gallery
version: 2.10.2+021002 # See README.md for details on versioning.

environment:
  flutter: ^3.13.0
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  adaptive_breakpoints: ^0.1.7
  animations: ^2.0.2
  collection: ^1.16.0
  cupertino_icons: ^1.0.4
  dual_screen: ^1.0.4
  flutter_gallery_assets: ^1.0.2
  flutter_localized_locales: ^2.0.4
  flutter_staggered_grid_view: ">=0.6.1 <0.8.0"
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  intl: any # An exact version pin will be provided by the Flutter SDK
  meta: ^1.11.0
  package_info_plus: ^5.0.1
  path_provider: ^2.0.11
  provider: ^6.0.2
  rally_assets: ^3.0.1
  scoped_model: ^2.0.0
  shrine_images: ^2.0.1
  transparent_image: ^2.0.1
  url_launcher: ^6.1.2
  vector_math: ^2.1.2
  dio: ^5.1.0
  image_picker: ^1.0.4
  flutter_markdown: ^0.6.18+2
  markdown: ^7.2.2
  string_scanner: ^1.2.0
  flutter_spinkit: ^5.2.0

flutter:
  generate: true # Enables generation of localized strings from arb files
  uses-material-design: true
  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
    - family: notosanssc
      fonts:
        - asset: fonts/NotoSansSC.otf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
  assets:
    - assets/images/chatgpt.png
    - assets/images/chatgpt_green.png
    - assets/images/chatgpt_red.png
    - assets/chat/rally_card.png
